# Generated by Django 2.0.4 on 2018-08-07 03:29

import django.core.validators
from django.db import migrations, models
import pybb.util


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0007_auto_20170111_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=pybb.util.FilePathGenerator(to='pybb_upload/attachments'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='File'),
        ),
    ]
