# Generated by Django 2.0.4 on 2019-04-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_auto_20180807_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='forum/attachments/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
